In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import sys
sys.path.append('/content/drive/MyDrive/AI systems Project/SummarIQ')

In [4]:
cd /content/drive/MyDrive/AI systems Project/SummarIQ

/content/drive/MyDrive/AI systems Project/SummarIQ

In [6]:
import pandas as pd
import re
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('bmh')
from pandas.plotting import scatter_matrix
from latex_extractor import LatexExtractor
# from pdf_conversion import PDFExtractor
import torch
import tf_keras as keras
from transformers import pipeline
import re

In [7]:
latexfiles_df = pd.read_json("latex_extracted.json")
latexfiles_df

,file_id,file_name,authors,title,text,equations
0,0087b54c-53c1-4fc5-ac2f-f9a5042def8d,sm.tex,[Ilya Karzhemanov],Computations and ML for surjective rational maps,The present note studies $f: ^2 ^2$ with terms...,[\label{diag} \xymatrix{\n& X \ar[dl]_\varphi ...

In [8]:
def prepare_input(row):
    text = row["text"]
    equations = row["equations"]
    combined = f"Paper Text:\n{text}\n\nEquations:\n{equations}"
    return combined

In [10]:
latexfiles_df["input_text"] = latexfiles_df.apply(prepare_input, axis=1)
latexfiles_df

,file_id,file_name,authors,title,text,equations,input_text
0,0087b54c-53c1-4fc5-ac2f-f9a5042def8d,sm.tex,[Ilya Karzhemanov],Computations and ML for surjective rational maps,The present note studies $f: ^2 ^2$ with terms...,[\label{diag} \xymatrix{\n& X \ar[dl]_\varphi ...,Paper Text:\nThe present note studies $f: ^2 ^...

In [11]:
latexfiles_df['input_text']

0    Paper Text:\nThe present note studies $f: ^2 ^...
Name: input_text, dtype: object